import Head from "next/head";
import { GetServerSideProps } from "next";
import { prisma } from "../../prisma/prisma";
import type { Category, Item } from "@prisma/client";
import Sidebar from "@/components/sidebar";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const categories = await prisma.category.findMany({
    include: { items: true },
  });

  return {
    props: {
      categoriesWithItems: categories,
    },
  };
};

type HomeProps = {
  categoriesWithItems: (Category & { items: Item[] })[];
};
export default function Home({ categoriesWithItems }: HomeProps) {
  return (
    <>
      <Head>
        <title>Shoppinify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <Sidebar />
        <div className="flex-auto">
          {categoriesWithItems.map((category) => (
            <div key={category.id}>
              <p>{category.name}</p>
              <ol>
                {category.items.map((item) => (
                  <li key={item.id}>
                    <button>{item.name}</button>
                  </li>
                ))}
              </ol>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
